name: MLflow CI Retraining - Advance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MLflow (for validation)
        run: |
          pip install mlflow

      # Retraining via MLflow Project (CI requirement)
      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local

      # Login Docker Hub (Advance requirement)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image (STABIL, TIDAK pakai MLflow CLI)
      - name: Build Docker Image
        run: |
          docker build -t telco-churn-mlflow:latest .

      # Tag & Push Image to Docker Hub
      - name: Tag and Push Docker Image
        run: |
          docker tag telco-churn-mlflow:latest ${{ secrets.DOCKER_USERNAME }}/telco-churn-mlflow:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/telco-churn-mlflow:latest
