name: MLflow CI Retraining - Advance

on:
  push:
    branches:
      - main

jobs:
  train-and-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install MLflow and scikit-learn
        run: |
          pip install mlflow scikit-learn pandas

      # Run MLflow Project (modelling.py akan dijalankan)
      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local

      # Upload MLflow artifacts (optional, untuk backup)
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns

      # Detect latest experiment & run
      - name: Detect latest MLflow run
        id: detect
        run: |
          EXP_ID=$(ls mlruns | head -n 1)
          RUN_ID=$(ls mlruns/$EXP_ID | sort | tail -n 1)
          echo "EXP_ID=$EXP_ID" >> $GITHUB_ENV
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Using EXP_ID=$EXP_ID, RUN_ID=$RUN_ID"

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image from MLflow model
      - name: Build Docker Image with MLflow
        run: |
          mlflow models build-docker \
            -m mlruns/${{ env.EXP_ID }}/${{ env.RUN_ID }}/artifacts/model \
            -n ${{ secrets.DOCKER_USERNAME }}/telco-churn-mlflow:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/telco-churn-mlflow:latest